stages:
  - test
  - merge

test:
  stage: test
  script:
    - wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - cd sf_app
    - ls
  only:
    - /^feature\/.*$/

merge:
  stage: merge
  script:
    - git config --global user.name "tylerjusfly"
    - git config --global user.email "tyler@sonnul.com"
    - git checkout main
    - git merge $CI_COMMIT_REF_NAME --no-ff
    - git push origin main
  only:
    - /^feature\/.*$/
  when: on_success
